
name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Example of using a custom build-command.
    # - uses: ammaraskar/sphinx-action@master
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "docs/"
        pre-build-command: "apt install --yes git build-essential pandoc"
        # pre-build-command: "python -m pip install sphinx-rtd-theme sphinx_automodapi nbsphinx"
        # build-command: "sphinx-build -b html . _build -D plot_formats='svg,pdf,hires.png'"
        build-command: "make html"
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/sedonaprice/sersic_profile_mass_VC.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
